import os, json, argparse
from pathlib import Path

def create_skill(name, desc, scope):
    skills_dir = Path(os.path.dirname(os.path.abspath(__file__))).parent.parent
    skill_dir = skills_dir / name
    
    if skill_dir.exists():
        print(f"Skill {name} already exists!")
        return
        
    for subdir in ["scripts", "references", "templates"]:
        (skill_dir / subdir).mkdir(parents=True, exist_ok=True)
        
    md_content = f"""---
name: {name}
description: {desc}
---

# {name}

> Auto-generated skill

## Instructions
1. Automatically generated by Parix Skill Forge.
"""
    (skill_dir / "SKILL.md").write_text(md_content, encoding="utf-8")
    
    # Update registry
    reg_path = skills_dir / "registry.json"
    registry = json.loads(reg_path.read_text(encoding="utf-8"))
    registry["skills"].append({"id": name, "path": f"skills/{name}/SKILL.md", "scope": scope})
    registry["loadOrder"].append(name)
    reg_path.write_text(json.dumps(registry, indent=2), encoding="utf-8")
    
    print(f"Successfully forged skill: {name}")

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--name", required=True)
    parser.add_argument("--desc", required=True)
    parser.add_argument("--scope", default="task")
    args = parser.parse_args()
    create_skill(args.name, args.desc, args.scope)
